name: Reusable Build and Deploy to AWS Amplify (Webhook)

on:
  workflow_call:
    inputs:
      artifact_dir:
        description: "Directory containing the build output"
        required: false
        type: string
        default: "build"

    secrets:
      AMPLIFY_WEBHOOK_URL:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        env: 
          CI: false

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ${{ inputs.artifact_dir }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist

      - name: Trigger AWS Amplify Deploy via Webhook
        run: |
          echo "Triggering Amplify deploy..."
          curl -X POST ${{ secrets.AMPLIFY_WEBHOOK_URL }}
